apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - orgId: 1
    name: testdata

# # list of datasources to insert/update depending
# # on what's available in the datbase
datasources:
  - orgId: 1
    name: TestData DB
    type: testdata
    isDefault: true
    version: 1
    editable: true
